name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:

  get-version-number:
    runs-on: windows-latest
    outputs:
      FLYWAY_VERSION: ${{ steps.step1.outputs.CURRENT_FLYWAY_VERSION }}
      CONTINUE: ${{ steps.step1.outputs.Continue }}
    steps:    
    - uses: actions/checkout@v2
    - id: step1
      name: Compare latest flyway version with container
      run: |
        $manifestDataRaw = Invoke-WebRequest "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/maven-metadata.xml"
        $manifestData = [Xml]$manifestDataRaw

        $latestFlywayVersion = $manifestData.metadata.versioning.latest

        $workerToolsTags = Invoke-RestMethod "https://registry.hub.docker.com/v2/repositories/octopuslabs/flyway-workertools/tags?page_size=50"
        $matchingTag = $workerToolsTags.results | Where-Object { $_.name -eq $latestFlywayVersion }

        echo "::set-output name=CURRENT_FLYWAY_VERSION::$latestFlywayVersion"

        if ($null -ne $matchingTag)
        {
            Write-Host "Docker container already has latest version of flyway"
            echo "::set-output name=Continue::No"
        }
        else
        {
            Write-Host "We need to upgrade the flyway container to $latestFlywayVersion"            
            echo "::set-output name=Continue::Yes"
        }      
      shell: powershell

  build-linux:
    needs: [get-version-number]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    
    - name: Dockerhub Login
      env:
        USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        PASSWORD: ${{ secrets.DOCKER_HUB_PAT }}
      run: docker login --username $USERNAME --password "$PASSWORD"
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
    
    - name: Build the Docker image
      env:
        FLYWAY_VERSION_TO_BUILD: ${{ needs.get-version-number.outputs.FLYWAY_VERSION }}
      run: docker build ./ubuntu-2004 --tag octopuslabs/flyway-workertools:$FLYWAY_VERSION_TO_BUILD-ubuntu.2004 --tag octopuslabs/flyway-workertools:latest-ubuntu.2004 --build-arg FLYWAY_VERSION=$FLYWAY_VERSION_TO_BUILD
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
      
    - name: Push the version image
      env:
        FLYWAY_VERSION_TO_BUILD: ${{ needs.get-version-number.outputs.FLYWAY_VERSION }}
      run: docker push octopuslabs/flyway-workertools:$FLYWAY_VERSION_TO_BUILD-ubuntu.2004
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
      
    - name: Push the latest image
      run: docker push octopuslabs/flyway-workertools:latest-ubuntu.2004
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
      
  build-windows-2019:
    needs: [get-version-number]
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
        
    - name: Dockerhub Login
      env:
        USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        PASSWORD: ${{ secrets.DOCKER_HUB_PAT }}
      run: docker login --username ${env:USERNAME} --password "${env:PASSWORD}"
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
    
    - name: Build the Docker image
      env:
        FLYWAY_VERSION_TO_BUILD: ${{ needs.get-version-number.outputs.FLYWAY_VERSION }}
      run: docker build ./windows-2019 --tag octopuslabs/flyway-workertools:${env:FLYWAY_VERSION_TO_BUILD}-windows.2019 --tag octopuslabs/flyway-workertools:latest-windows.2019 --build-arg FLYWAY_VERSION=${env:FLYWAY_VERSION_TO_BUILD}
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
      
    - name: Push the version image
      env:
        FLYWAY_VERSION_TO_BUILD: ${{ needs.get-version-number.outputs.FLYWAY_VERSION }}
      run: docker push octopuslabs/flyway-workertools:${env:FLYWAY_VERSION_TO_BUILD}-windows.2019
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
      
    - name: Push the latest image
      run: docker push octopuslabs/flyway-workertools:latest-windows.2019
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
  
  build-docker-manifest:
    needs: [build-windows-2019, build-linux, get-version-number]
    runs-on: ubuntu-latest
    
    steps:
    - name: Dockerhub Login
      env:
        USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        PASSWORD: ${{ secrets.DOCKER_HUB_PAT }}
      run: docker login --username $USERNAME --password "$PASSWORD"
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
      
    - name: Build Manifest
      run: docker manifest create octopuslabs/flyway-workertools:latest octopuslabs/flyway-workertools:latest-windows.2019 octopuslabs/flyway-workertools:latest-ubuntu.2004
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
      
    - name: Push Manifest
      run: docker manifest push octopuslabs/flyway-workertools:latest
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
      
    - name: Build Version Manifest      
      env:
        FLYWAY_VERSION_TO_BUILD: ${{ needs.get-version-number.outputs.FLYWAY_VERSION }}      
      run: docker manifest create octopuslabs/flyway-workertools:$FLYWAY_VERSION_TO_BUILD octopuslabs/flyway-workertools:$FLYWAY_VERSION_TO_BUILD-windows.2019 octopuslabs/flyway-workertools:$FLYWAY_VERSION_TO_BUILD-ubuntu.2004
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
      
    - name: Push Version Manifest
      env:
        FLYWAY_VERSION_TO_BUILD: ${{ needs.get-version-number.outputs.FLYWAY_VERSION }}
      run: docker manifest push octopuslabs/flyway-workertools:$FLYWAY_VERSION_TO_BUILD
      if: ${{ needs.get-version-number.outputs.CONTINUE == 'Yes' }}
  
