name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    
    - name: Build the Docker image
      run: docker build ./ubuntu-1804 --tag octopuslabs/flyway-workertools:7.7.1-ubuntu.1804 --tag octopuslabs/flyway-workertools:latest-ubuntu.1804
      
    - name: Push the version image
      run: docker push octopuslabs/flyway-workertools:7.7.1-ubuntu.1804
      
    - name: Push the latest image
      run: docker push octopuslabs/flyway-workertools:latest-ubuntu.1804
      
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PAT }}
    
    - name: Build the Docker image
      run: docker build ./windows-2019 --tag octopuslabs/flyway-workertools:7.7.1-windows.2019 --tag octopuslabs/flyway-workertools:latest-windows.2019
      
    - name: Push the version image
      run: docker push octopuslabs/flyway-workertools:7.7.1-windows.2019
      
    - name: Push the latest image
      run: docker push octopuslabs/flyway-workertools:latest-windows.2019
